INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (1, 'Marie', 'Maéva', '6118 Lorem Ave', 'facilisis@utsemNulla.com', '1953-04-21');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (2, 'Roux', 'Kylian', 'CP 204, 7528 Placerat, Chemin', 'Donec.egestas@ullamcorperDuisat.co.uk', '1973-12-02');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (3, 'Guillot', 'Noémie', 'Appartement 392-6321 Massa. Rue', 'Suspendisse.sed@ipsumporta.co.uk', '1961-11-30');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (4, 'Breton', 'Lola', 'CP 861, 5902 Justo. Avenue', 'a.tortor@arcuCurabiturut.edu', '1978-03-15');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (5, 'Durand', 'Sara', '931-6077 Dictum Chemin', 'at.pretium.aliquet@tellusAenean.com', '1956-11-12');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (6, 'Baron', 'Charlotte', '260-485 Malesuada Route', 'natoque.penatibus@sagittisDuisgravida.co.uk', '1952-09-27');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (7, 'Lefevre', 'Léonard', 'Appartement 705-2319 Nisi. Ave', 'ligula.eu@mitempor.net', '1966-01-05');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (8, 'Martinez', 'Loane', '160-6351 Nam Avenue', 'ac.mattis@urnaVivamusmolestie.net', '1964-03-29');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (9, 'Julien', 'Adrien', 'Appartement 460-8666 Molestie Ave', 'a.sollicitudin.orci@arcuAliquamultrices.edu', '1980-04-12');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (10, 'Rodriguez', 'Léonie', 'Appartement 263-8914 Ut Av.', 'sociis.natoque@lobortis.co.uk', '1984-02-25');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (11, 'Joly', 'Lorenzo', '487-6623 Ante. Avenue', 'vel.nisl.Quisque@utmi.org', '1970-02-04');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (12, 'Dufour', 'Tom', 'Appartement 707-2041 Dolor Chemin', 'tempor.lorem@primisinfaucibus.org', '1959-06-12');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (13, 'Remy', 'Jordan', 'Appartement 168-2146 Dui. Avenue', 'lobortis.tellus.justo@Morbi.ca', '1951-10-01');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (14, 'Bertrand', 'Simon', '280-276 Pede Ave', 'fringilla.mi@molestiepharetranibh.edu', '1960-09-25');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (15, 'Leclerc', 'Mélissa', '7890 Enim, Route', 'neque.sed@Phasellusfermentum.com', '1971-08-30');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (16, 'Roy', 'Kyllian', '3704 Auctor Ave', 'nec.cursus@nuncsed.net', '1963-11-09');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (17, 'Caron', 'Emma', '510 Cum Rd.', 'libero.est.congue@vitaedolorDonec.net', '1966-06-08');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (18, 'Leveque', 'Pauline', 'Appartement 626-3969 Orci Ave', 'Aenean.euismod@neque.co.uk', '1951-04-04');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (19, 'Paris', 'Margot', '7764 Leo. Avenue', 'lectus.convallis@dictummagna.ca', '1979-11-16');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (20, 'Dumas', 'Anaël', '6892 Etiam Impasse', 'ipsum.sodales@Duis.edu', '1981-12-17');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (21, 'Duval', 'Cloé', 'Appartement 149-802 Convallis Av.', 'et.malesuada.fames@aliquetmetus.org', '1952-03-29');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (22, 'Fernandez', 'Florian', '207-5685 Eu Av.', 'semper.tellus.id@aliquetsemut.ca', '1970-12-23');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (23, 'Giraud', 'Carla', 'Appartement 204-5129 Vitae Rue', 'Cum.sociis@pharetrasedhendrerit.org', '1987-02-07');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (24, 'Marie', 'Gabriel', '877-3618 Vulputate, Avenue', 'lectus@sociisnatoquepenatibus.ca', '1984-07-11');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (25, 'Lemoine', 'Laura', 'Appartement 814-4968 Est, Rue', 'pellentesque.tellus.sem@auctor.org', '1955-04-09');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (26, 'Colin', 'Charlotte', '8166 Nec, Av.', 'sapien@aliquet.org', '1961-02-07');
INSERT INTO univ.Conseiller (id, nom, prenom, adresse, email, dateNaissance) VALUES (27, 'Charpentier', 'Lily', '5325 Fermentum Route', 'sit.amet@urnanec.net', '1950-10-05');