INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Algo1', 'Algorithmes', 3, 'Algorithmiques', 79);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Algo2', 'Algorithmes avancées', 4, 'Algorithmiques', 79);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Ana0', 'Analyse (suites et fonctions de variables réelles en dimension 1)', 1, 'Analyse mathématique', 3);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Ana1', 'Analyse (suites et fonctions de variables réelles en dimension n)', 2, 'Analyse mathématique', 3);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Ana2', 'Equation différentielles ordinaires', 3, 'Analyse mathématique', 3);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Ana3', 'Résolution analytiques des EDP', 3, 'Analyse mathématique', 3);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Ana4', 'Analyse fonctionnel', 4, 'Analyse mathématique', 3);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Comb0', 'Initiation à l’analyse combinatoire (graphes, etc)', 2, 'Combinatoires', 15);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Comb1', 'Combinatoires avancées', 3, 'Combinatoires', 15);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Comb2', 'Optimisation combinatoire', 4, 'Combinatoires', 15);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Comp0', 'Automates, langages, regex', 4, 'Algorithmiques', 79);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Comp1', 'Langages et compilateurs', 4, 'Algorithmiques', 79);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Comp2', 'Compilateurs et assembleur', 4, 'Algorithmiques', 79);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Complex0', 'Les nombres complexes - applications géometriques', 1, 'Analyse complexe', 23);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Complex1', 'Analyse complexe', 3, 'Analyse complexe', 23);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Complex2', 'Analyse complexe – approfondissement', 4, 'Analyse complexe', 23);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Control1', 'Théorie de contrôle', 3, 'Contrôle et automatique', 7);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Control2', 'Système dynamiques, théorie de contrôle', 3, 'Contrôle et automatique', 7);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Control3', 'Système dynamiques, théorie du chaos', 4, 'Contrôle et automatique', 7);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Data0', 'Base de données et SQL', 2, 'Sciences de données', 86);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Data1', 'Base de données avancé', 3, 'Sciences de données', 86);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Data2', 'Découverte de big data et algorithmes', 3, 'Sciences de données', 86);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Data3', 'Big data – avancé', 4, 'Sciences de données', 86);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('DevWeb0', 'Créations de sites pour les non informaticiens', 1, 'Développement Web', 77);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('DevWeb1', 'Développement Web', 3, 'Développement Web', 77);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Elec0', 'Electromagnétisme et courant alternatif', 2, 'Electronique', 42);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Elec1', 'Electromagnétisme avancé', 3, 'Electronique', 42);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Elec2', 'Physique quantique, electronique, et applications', 2, 'Electronique', 42);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Elec3', 'Electricité – avancé', 3, 'Electronique', 42);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnA1', 'Anglais niveau A1 (intensif)', 2, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnA11', 'Anglais niveau A1.1', 1, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnA12', 'Anglais niveau A1.2', 1, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnA2', 'Anglais niveau A2 (intensif)', 2, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnA21', 'Anglais niveau A2.1', 1, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnA22', 'Anglais niveau A2.2', 1, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnB1', 'Anglais niveau B1 (intensif)', 2, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnB11', 'Anglais niveau B1.1', 1, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnB12', 'Anglais niveau B1.2', 1, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnB2', 'Anglais niveau B2 (intensif)', 2, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnB21', 'Anglais niveau B2.1', 1, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnB22', 'Anglais niveau B2.2', 1, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnC1', 'Anglais niveau C1 (intensif)', 3, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('EnC2', 'Anglais niveau C2 (intensif)', 3, 'Langue anglaise', 91);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Fluid0', 'Initiation à la mécanique des fluides', 2, 'Mécanique des fluides', 50);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Fluid1', 'Mecanique des fluides', 3, 'Mécanique des fluides', 50);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Fluid2', 'Turbulances, dyphasique, etc', 4, 'Mécanique des fluides', 50);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Fluid3', 'Mecanique des fluides avancée', 4, 'Mécanique des fluides', 50);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Fourier1', 'La famille de transformations de fourier', 3, 'Analyse de fourier', 23);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Fourier2', 'Approfondissement dans l’analyse de fourier', 4, 'Analyse de fourier', 23);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('LinAlg0', 'Trigonometrie et géometrie dans l’espace 3D', 1, 'Algèbre linéaire', 1);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('LinAlg1', 'Th. des groupes, espaces vectoriels, app. Linéaires', 2, 'Algèbre linéaire', 1);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('LinAlg2', 'Algèbre Linéaire – approfondissement', 3, 'Algèbre linéaire', 1);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Logic0', 'Logique, initation à la métamathématique, la méthode scientifique', 2, 'Logique', 19);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Logic1', 'Logique mathématique avancé', 3, 'Logique', 19);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Logic2', 'Logique mathématique avancé – approfondissement', 5, 'Logique', 19);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Logic3', 'Programmation logique', 3, 'Logique', 19);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Mat1', 'Matériaux (initiation)', 2, 'Etudes de matériaux', 57);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Mat2', 'Matériaux (avancé)', 3, 'Etudes de matériaux', 57);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Meca0', 'Physique Newtonienne (base de mécanique du point + applications)', 1, 'Mécanique fondamentale', 40);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Meca1', 'Mécanique du point et relativité', 3, 'Mécanique fondamentale', 40);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Mesure0', 'Théorie des ensembles', 1, 'Théorie de la mesure', 13);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Mesure1', 'Théorie de la mesure', 3, 'Théorie de la mesure', 13);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Model0', 'Initiation à la modélisation', 3, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Model1', 'Modèlisation avancée', 3, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Music0', 'Base de la théorie de la musique occidentale et initiation au solfège', 1, 'Théorie de la musique', 115);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Music1', 'Théories de musique', 3, 'Théorie de la musique', 115);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Music2', 'Composition (théories)', 4, 'Théorie de la musique', 115);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Net0', 'Résaux informatique (générales)', 2, 'Résaux', 75);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Net1', 'Résaux – avancé', 3, 'Résaux', 75);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Num0', 'Contraintes numériques de l’ordinateurs – erreurs – algorithmes', 3, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Num1', 'Méthodes numériques générales (système linéaires, equations différentielles)', 3, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Num2', 'Résolution de système linéaires', 3, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Num3', 'Approximation de fonctions (interpolation, quadrature)', 3, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Num4', 'Résolution numérique des EDO et EDP', 4, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Num5', 'Résolution numérique des EDP (avancé)', 4, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Num6', 'Résolution numérique – approfondissement', 4, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Num7', 'Approximation de fonctions (Bezier, Splines, etc)', 4, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Optique0', 'Optique géométriques', 1, 'Physique optique', 55);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Optique1', 'Optique ondulatoires', 3, 'Physique optique', 55);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Proba0', 'Initiation à la probablité (discrète)', 1, 'Probabilités et statistiques', 11);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Proba1', 'Probabilité discrète et continue, var aléatoires, loi des grandes nombres', 2, 'Probabilités et statistiques', 11);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Proba2', 'Processus stochastiques', 3, 'Probabilités et statistiques', 11);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Prog0', 'Initiation à la programmation', 2, 'Programmation', 65);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Prog1', 'Exercices de programmation', 2, 'Programmation', 65);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Prog2', 'Programmation avancé et structures de données', 3, 'Programmation', 65);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Prog3', 'POO + UML + génie logiciel', 3, 'Programmation', 65);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Prog4', 'Programmation d’interfaces graphiques', 3, 'Programmation', 65);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('ProgLin', 'Programmation linéaire', 3, 'Méthodes numériques et modélisation', 30);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Signal1', 'Analyse de signal – théorie et application', 3, 'Traitement de signal', 27);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Signal2', 'Signal aléatoire, filtrage, etc', 3, 'Traitement de signal', 27);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Signal3', 'Traitement de son', 4, 'Traitement de signal', 27);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Signal4', 'Traitement d’image', 4, 'Traitement de signal', 27);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Stats1', 'Initiation aux statistiques – estimateurs', 3, 'Probabilités et statistiques', 11);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Stats2', 'Modèles statistiques avancées', 3, 'Probabilités et statistiques', 11);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Stats3', 'Méthodes statistiques pour l’analyse de données', 3, 'Probabilités et statistiques', 11);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Techno0', 'Architecture de l’ordinateur (culture générale)', 1, 'Technologies', 59);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Techno1', 'Systèmes d’exploitations, logiciels (culture générale)', 1, 'Technologies', 59);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Techno2', 'Maintenance de problèmes courants', 2, 'Technologies', 59);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Thermo0', 'Initiation à la thermodynamique', 2, 'Thermodynamique', 46);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Thermo1', 'Modèles thermodynamiques', 2, 'Thermodynamique', 46);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Thermo2', 'Thermodynamique chimique', 2, 'Thermodynamique', 46);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Thermo3', 'Thermodynamique avancée', 3, 'Thermodynamique', 46);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Topo0', 'Initiation à la topologie (générale et algébrique)', 2, 'Topologie', 9);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Topo1', 'Topologie géometrique', 3, 'Topologie', 9);
INSERT INTO univ.Matiere (code, nom, credits, nomDomaine, respoDomaine) VALUES ('Topo2', 'Topologie – approfondissement', 4, 'Topologie', 9);